package com.java8;/** * @Author：liuyl * @Date：2022-07-13 */public class TryCatch {    public static void main(String[] args) {        System.out.println("开始");        // try {} catch() {}，当try中的执行发生异常后，就执行catch中的，之后跳出catch，继续往下执行        try {            // 该处发生数组越界异常后，执行catch中的            a1();            System.out.println("无异常，不会进入catch");        } catch (ArrayIndexOutOfBoundsException e) {            System.out.println("数组越界，访问异常进入catch");            e.printStackTrace();        }        // 程序继续往下执行        System.out.println("结束");    }    public static void a1() {        int[] arrs = {1, 8, 9};        //报错：数组越界一异常        System.out.println(arrs[3]);    }}